# Standalone PaiNN + Frame-Conditioned Vector Mixer (FCVM-Stage1)
# - No schnetpack dependency
# - Optional naive radius-graph builder (O(N^2) per molecule)
#
# Input conventions (matching the uploaded properties.py):
#   - idx_i: center atoms
#   - idx_j: neighboring atoms
#   - Rij: vectors pointing from center atoms i to neighboring atoms j (Rj - Ri)
#
# Author: generated by ChatGPT

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional, Tuple, Callable, List

import torch
import torch.nn as nn
import torch.nn.functional as F


# ----------------------------
# Small utilities
# ----------------------------

def scatter_add(src: torch.Tensor, index: torch.Tensor, dim_size: int) -> torch.Tensor:
    """
    Minimal scatter_add on dim=0 using index_add_.
    src: [E, ...]
    index: [E] with values in [0, dim_size-1]
    returns: [dim_size, ...]
    """
    out = torch.zeros((dim_size,) + src.shape[1:], dtype=src.dtype, device=src.device)
    out.index_add_(0, index, src)
    return out


def safe_norm(x: torch.Tensor, dim: int = -1, keepdim: bool = False, eps: float = 1e-9) -> torch.Tensor:
    return torch.sqrt(torch.sum(x * x, dim=dim, keepdim=keepdim) + eps)


# ----------------------------
# Graph building (naive, optional)
# ----------------------------

@torch.no_grad()
def radius_graph_naive(
    R: torch.Tensor,
    cutoff: float,
    batch: Optional[torch.Tensor] = None,
    max_num_neighbors: Optional[int] = None,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Build radius graph with optional max neighbors per center atom.
    This is a naive O(N^2) implementation, intended for small molecules / debugging.

    Args:
        R: [N, 3]
        cutoff: float
        batch: [N] long, molecule id per atom. If None, treat as single system.
        max_num_neighbors: optional cap per center i (keep nearest neighbors)

    Returns:
        idx_i: [E]
        idx_j: [E]
        Rij:  [E, 3] = Rj - Ri
    """
    device = R.device
    if batch is None:
        batch = torch.zeros((R.shape[0],), device=device, dtype=torch.long)

    idx_i_all: List[torch.Tensor] = []
    idx_j_all: List[torch.Tensor] = []
    rij_all: List[torch.Tensor] = []

    unique = torch.unique(batch).tolist()
    for b in unique:
        mask = batch == b
        ids = torch.nonzero(mask, as_tuple=False).squeeze(-1)  # global indices
        Rb = R[ids]  # [Nb,3]
        Nb = Rb.shape[0]
        if Nb <= 1:
            continue

        diff = Rb[None, :, :] - Rb[:, None, :]  # [Nb,Nb,3] = Rj - Ri
        dist = safe_norm(diff, dim=-1, keepdim=False)          # [Nb,Nb]
        # exclude self
        dist.fill_diagonal_(cutoff + 1.0)

        within = dist < cutoff
        ii, jj = torch.nonzero(within, as_tuple=True)
        if ii.numel() == 0:
            continue

        if max_num_neighbors is not None:
            kept_mask = torch.zeros_like(ii, dtype=torch.bool)
            for i_local in range(Nb):
                sel = (ii == i_local)
                if not torch.any(sel):
                    continue
                d = dist[i_local, jj[sel]]
                k = min(int(max_num_neighbors), int(d.numel()))
                topk = torch.topk(d, k=k, largest=False).indices
                sel_idx = torch.nonzero(sel, as_tuple=False).squeeze(-1)
                kept_mask[sel_idx[topk]] = True
            ii = ii[kept_mask]
            jj = jj[kept_mask]

        idx_i = ids[ii]
        idx_j = ids[jj]
        rij = R[idx_j] - R[idx_i]

        idx_i_all.append(idx_i)
        idx_j_all.append(idx_j)
        rij_all.append(rij)

    if len(idx_i_all) == 0:
        return (
            torch.empty((0,), device=device, dtype=torch.long),
            torch.empty((0,), device=device, dtype=torch.long),
            torch.empty((0, 3), device=device, dtype=R.dtype),
        )

    idx_i = torch.cat(idx_i_all, dim=0)
    idx_j = torch.cat(idx_j_all, dim=0)
    Rij = torch.cat(rij_all, dim=0)
    return idx_i, idx_j, Rij


# ----------------------------
# Radial basis + cutoff
# ----------------------------

class GaussianRBF(nn.Module):
    def __init__(self, n_rbf: int, cutoff: float, trainable: bool = False):
        super().__init__()
        self.n_rbf = int(n_rbf)
        self.cutoff = float(cutoff)

        centers = torch.linspace(0.0, cutoff, n_rbf)
        widths = torch.full((n_rbf,), (centers[1] - centers[0]).item() if n_rbf > 1 else cutoff)

        if trainable:
            self.centers = nn.Parameter(centers)
            self.widths = nn.Parameter(widths)
        else:
            self.register_buffer("centers", centers)
            self.register_buffer("widths", widths)

    def forward(self, d: torch.Tensor) -> torch.Tensor:
        diff = d - self.centers.view(1, -1)
        return torch.exp(-0.5 * (diff / (self.widths.view(1, -1) + 1e-12)) ** 2)


class CosineCutoff(nn.Module):
    def __init__(self, cutoff: float):
        super().__init__()
        self.cutoff = float(cutoff)

    def forward(self, d: torch.Tensor) -> torch.Tensor:
        x = d / self.cutoff
        out = 0.5 * (torch.cos(torch.clamp(x, 0.0, 1.0) * torch.pi) + 1.0)
        return out * (d <= self.cutoff).to(d.dtype)


# ----------------------------
# Dense (like schnetpack.nn.Dense)
# ----------------------------

class Dense(nn.Module):
    def __init__(self, in_features: int, out_features: int, activation: Optional[Callable] = None, bias: bool = True):
        super().__init__()
        self.linear = nn.Linear(in_features, out_features, bias=bias)
        self.activation = activation

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y = self.linear(x)
        if self.activation is None:
            return y
        return self.activation(y)


# ----------------------------
# Local frame construction
# ----------------------------

def build_local_frame(
    dir_ij: torch.Tensor,  # [E,3]
    idx_i: torch.Tensor,   # [E]
    n_atoms: int,
    eps: float = 1e-9,
) -> torch.Tensor:
    """
    Build a per-atom right-handed local frame [N,3,3] from neighbor directions.
    e1: normalized mean direction
    e2: normalized mean (dir^2) after removing projection on e1 (fallback if degenerate)
    e3: cross(e1, e2)
    """
    w = torch.ones((dir_ij.shape[0], 1), dtype=dir_ij.dtype, device=dir_ij.device)

    m1 = scatter_add(w * dir_ij, idx_i, dim_size=n_atoms)  # [N,3]
    e1 = m1 / safe_norm(m1, dim=-1, keepdim=True, eps=eps)  # [N,3]

    m2 = scatter_add(w * (dir_ij ** 2), idx_i, dim_size=n_atoms)  # [N,3]
    proj = torch.sum(m2 * e1, dim=-1, keepdim=True) * e1
    u2 = m2 - proj
    u2_norm = safe_norm(u2, dim=-1, keepdim=True, eps=eps)

    fallback = torch.tensor([1.0, 0.0, 0.0], device=dir_ij.device, dtype=dir_ij.dtype).view(1, 3).repeat(n_atoms, 1)
    parallel = (torch.abs(torch.sum(e1 * fallback, dim=-1, keepdim=True)) > 0.9).to(dir_ij.dtype)
    fallback = fallback * (1.0 - parallel) + torch.tensor([0.0, 1.0, 0.0], device=dir_ij.device, dtype=dir_ij.dtype).view(1, 3) * parallel

    u2 = torch.where(u2_norm < 1e-6, fallback - torch.sum(fallback * e1, dim=-1, keepdim=True) * e1, u2)
    e2 = u2 / safe_norm(u2, dim=-1, keepdim=True, eps=eps)

    e3 = torch.cross(e1, e2, dim=-1)
    e3 = e3 / safe_norm(e3, dim=-1, keepdim=True, eps=eps)

    e2 = torch.cross(e3, e1, dim=-1)
    e2 = e2 / safe_norm(e2, dim=-1, keepdim=True, eps=eps)

    frame = torch.stack([e1, e2, e3], dim=-1)  # [N,3,3]
    return frame


# ----------------------------
# PaiNN blocks (with FCVM gate)
# ----------------------------

class PaiNNInteractionFCVM(nn.Module):
    """
    PaiNN interaction block augmented with FCVM-Stage1:
      - project muj onto local frame at centers i
      - gate dmuR and dmumu based on (projection + scalar edge context)
    """

    def __init__(self, n_atom_basis: int, n_rbf: int, activation: Callable = F.silu):
        super().__init__()
        self.n_atom_basis = int(n_atom_basis)

        self.interatomic_context_net = nn.Sequential(
            Dense(n_atom_basis, n_atom_basis, activation=activation),
            Dense(n_atom_basis, 3 * n_atom_basis, activation=None),
        )

        self.edge_gate_net = nn.Sequential(
            Dense(2 * n_atom_basis + n_rbf, n_atom_basis, activation=activation),
            Dense(n_atom_basis, 2 * n_atom_basis, activation=None),
        )
        self.proj_gate = nn.Linear(3, 2, bias=True)

        self.gate_dq = False

    def forward(
        self,
        q: torch.Tensor,          # [N,1,C]
        mu: torch.Tensor,         # [N,3,C]
        Wij: torch.Tensor,        # [E,1,3C]
        dir_ij: torch.Tensor,     # [E,3]
        phi_ij: torch.Tensor,     # [E,n_rbf]
        idx_i: torch.Tensor,      # [E]
        idx_j: torch.Tensor,      # [E]
        n_atoms: int,
        node_frame: Optional[torch.Tensor] = None,  # [N,3,3]
        chirality_invariant: bool = False,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        x = self.interatomic_context_net(q)  # [N,1,3C]
        xj = x[idx_j]                        # [E,1,3C]
        muj = mu[idx_j]                      # [E,3,C]
        x = Wij * xj                         # [E,1,3C]

        dq, dmuR, dmumu = torch.split(x, self.n_atom_basis, dim=-1)  # [E,1,C]

        if node_frame is None:
            node_frame = build_local_frame(dir_ij, idx_i, n_atoms=n_atoms)  # [N,3,3]
        Fi = node_frame[idx_i]  # [E,3,3]
        e1 = Fi[:, :, 0]
        e2 = Fi[:, :, 1]
        e3 = Fi[:, :, 2]

        p1 = torch.sum(muj * e1[:, :, None], dim=1)  # [E,C]
        p2 = torch.sum(muj * e2[:, :, None], dim=1)
        p3 = torch.sum(muj * e3[:, :, None], dim=1)
        if chirality_invariant:
            p2 = torch.abs(p2)

        p = torch.stack([p1, p2, p3], dim=-1)  # [E,C,3]
        proj_logits = self.proj_gate(p)        # [E,C,2]

        qi = q[idx_i].squeeze(1)  # [E,C]
        qj = q[idx_j].squeeze(1)  # [E,C]
        edge_in = torch.cat([qi, qj, phi_ij], dim=-1)  # [E,2C+n_rbf]
        edge_logits = self.edge_gate_net(edge_in).view(-1, self.n_atom_basis, 2)  # [E,C,2]

        gate = torch.sigmoid(edge_logits + proj_logits)  # [E,C,2]
        g_r = gate[:, :, 0].unsqueeze(1)   # [E,1,C]
        g_mu = gate[:, :, 1].unsqueeze(1)  # [E,1,C]

        dmuR = dmuR * g_r
        dmumu = dmumu * g_mu
        if self.gate_dq:
            dq = dq * (0.5 * (g_r + g_mu))

        dq_agg = scatter_add(dq, idx_i, dim_size=n_atoms)  # [N,1,C]
        dmu = dmuR * dir_ij[..., None] + dmumu * muj       # [E,3,C]
        dmu_agg = scatter_add(dmu, idx_i, dim_size=n_atoms)  # [N,3,C]

        return q + dq_agg, mu + dmu_agg


class PaiNNMixing(nn.Module):
    def __init__(self, n_atom_basis: int, activation: Callable = F.silu, epsilon: float = 1e-8):
        super().__init__()
        self.n_atom_basis = int(n_atom_basis)
        self.intraatomic_context_net = nn.Sequential(
            Dense(2 * n_atom_basis, n_atom_basis, activation=activation),
            Dense(n_atom_basis, 3 * n_atom_basis, activation=None),
        )
        self.mu_channel_mix = Dense(n_atom_basis, 2 * n_atom_basis, activation=None, bias=False)
        self.epsilon = float(epsilon)

    def forward(self, q: torch.Tensor, mu: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        mu_mix = self.mu_channel_mix(mu)  # [N,3,2C]
        mu_V, mu_W = torch.split(mu_mix, self.n_atom_basis, dim=-1)  # [N,3,C]
        mu_Vn = torch.sqrt(torch.sum(mu_V ** 2, dim=-2, keepdim=True) + self.epsilon)  # [N,1,C]

        ctx = torch.cat([q, mu_Vn], dim=-1)  # [N,1,2C]
        x = self.intraatomic_context_net(ctx)  # [N,1,3C]
        dq_intra, dmu_intra, dqmu_intra = torch.split(x, self.n_atom_basis, dim=-1)
        dmu_intra = dmu_intra * mu_W
        dqmu_intra = dqmu_intra * torch.sum(mu_V * mu_W, dim=1, keepdim=True)

        return q + dq_intra + dqmu_intra, mu + dmu_intra


# ----------------------------
# Full model
# ----------------------------

@dataclass
class PaiNNConfig:
    n_atom_basis: int = 128
    n_interactions: int = 3
    cutoff: float = 5.0
    n_rbf: int = 64
    max_num_neighbors: Optional[int] = None  # only used for naive graph builder
    epsilon: float = 1e-8
    chirality_invariant: bool = False
    shared_interactions: bool = False
    shared_filters: bool = False
    build_graph: bool = False  # if True, build idx_i/idx_j/Rij from positions (slow)


class StandalonePaiNN_FCVM(nn.Module):
    """
    Fully standalone model:
      - GaussianRBF + CosineCutoff
      - PaiNN + FCVM-Stage1 gating
      - Atom-wise energy head + sum pooling
      - Optional forces via autograd
    """

    def __init__(self, cfg: PaiNNConfig):
        super().__init__()
        self.cfg = cfg

        self.radial_basis = GaussianRBF(cfg.n_rbf, cfg.cutoff, trainable=False)
        self.cutoff_fn = CosineCutoff(cfg.cutoff)

        self.embedding = nn.Embedding(100, cfg.n_atom_basis)

        self.share_filters = bool(cfg.shared_filters)
        if self.share_filters:
            self.filter_net = Dense(cfg.n_rbf, 3 * cfg.n_atom_basis, activation=None)
        else:
            self.filter_net = Dense(cfg.n_rbf, cfg.n_interactions * 3 * cfg.n_atom_basis, activation=None)

        if cfg.shared_interactions:
            shared = PaiNNInteractionFCVM(cfg.n_atom_basis, cfg.n_rbf, activation=F.silu)
            self.interactions = nn.ModuleList([shared for _ in range(cfg.n_interactions)])
            shared_m = PaiNNMixing(cfg.n_atom_basis, activation=F.silu, epsilon=cfg.epsilon)
            self.mixing = nn.ModuleList([shared_m for _ in range(cfg.n_interactions)])
        else:
            self.interactions = nn.ModuleList([
                PaiNNInteractionFCVM(cfg.n_atom_basis, cfg.n_rbf, activation=F.silu)
                for _ in range(cfg.n_interactions)
            ])
            self.mixing = nn.ModuleList([
                PaiNNMixing(cfg.n_atom_basis, activation=F.silu, epsilon=cfg.epsilon)
                for _ in range(cfg.n_interactions)
            ])

        self.energy_head = nn.Sequential(
            Dense(cfg.n_atom_basis, cfg.n_atom_basis, activation=F.silu),
            Dense(cfg.n_atom_basis, 1, activation=None),
        )

    def forward(
        self,
        atomic_numbers: torch.Tensor,  # [N]
        positions: Optional[torch.Tensor] = None,  # [N,3]
        idx_i: Optional[torch.Tensor] = None,      # [E]
        idx_j: Optional[torch.Tensor] = None,      # [E]
        Rij: Optional[torch.Tensor] = None,        # [E,3]
        batch: Optional[torch.Tensor] = None,      # [N]
        compute_forces: bool = False,
        return_representation: bool = False,
    ) -> Dict[str, torch.Tensor]:
        if self.cfg.build_graph:
            if positions is None:
                raise ValueError("positions is required when cfg.build_graph=True")
            idx_i, idx_j, Rij = radius_graph_naive(
                positions, cutoff=self.cfg.cutoff, batch=batch, max_num_neighbors=self.cfg.max_num_neighbors
            )
        else:
            if idx_i is None or idx_j is None or Rij is None:
                raise ValueError("idx_i, idx_j, Rij are required when cfg.build_graph=False")

        if compute_forces and positions is None:
            raise ValueError("positions is required when compute_forces=True")

        n_atoms = atomic_numbers.shape[0]
        d_ij = safe_norm(Rij, dim=-1, keepdim=True, eps=1e-12)  # [E,1]
        dir_ij = Rij / d_ij                                     # [E,3]
        phi_ij = self.radial_basis(d_ij)                        # [E,n_rbf]
        fcut = self.cutoff_fn(d_ij)                             # [E,1]

        filters = self.filter_net(phi_ij) * fcut                # [E,3C] or [E,n_int*3C]
        if self.share_filters:
            filter_list = [filters.unsqueeze(1)] * self.cfg.n_interactions
        else:
            parts = torch.split(filters, 3 * self.cfg.n_atom_basis, dim=-1)
            filter_list = [p.unsqueeze(1) for p in parts]

        q = self.embedding(atomic_numbers).unsqueeze(1)  # [N,1,C]
        mu = torch.zeros((n_atoms, 3, self.cfg.n_atom_basis), device=q.device, dtype=q.dtype)

        node_frame = build_local_frame(dir_ij, idx_i, n_atoms=n_atoms)  # [N,3,3]

        for interaction, mixing, Wij in zip(self.interactions, self.mixing, filter_list):
            q, mu = interaction(
                q=q,
                mu=mu,
                Wij=Wij,
                dir_ij=dir_ij,
                phi_ij=phi_ij,
                idx_i=idx_i,
                idx_j=idx_j,
                n_atoms=n_atoms,
                node_frame=node_frame,
                chirality_invariant=self.cfg.chirality_invariant,
            )
            q, mu = mixing(q, mu)

        q_out = q.squeeze(1)  # [N,C]
        e_atom = self.energy_head(q_out).squeeze(-1)  # [N]

        if batch is None:
            energy = e_atom.sum(dim=0, keepdim=True)  # [1]
        else:
            n_sys = int(batch.max().item()) + 1 if batch.numel() > 0 else 1
            energy = scatter_add(e_atom.unsqueeze(-1), batch, dim_size=n_sys).squeeze(-1)  # [B]

        out: Dict[str, torch.Tensor] = {"energy": energy}

        if compute_forces:
            total = energy.sum()
            forces = -torch.autograd.grad(total, positions, create_graph=True, retain_graph=True)[0]
            out["forces"] = forces

        if return_representation:
            out["scalar_representation"] = q_out
            out["vector_representation"] = mu

        return out


if __name__ == "__main__":
    torch.manual_seed(0)
    cfg = PaiNNConfig(n_atom_basis=64, n_interactions=2, cutoff=5.0, n_rbf=32, build_graph=True, max_num_neighbors=32)
    model = StandalonePaiNN_FCVM(cfg)

    Z = torch.tensor([6, 1, 1, 1, 1], dtype=torch.long)
    R = torch.randn(5, 3, requires_grad=True)
    batch = torch.zeros(5, dtype=torch.long)

    out = model(Z, positions=R, batch=batch, compute_forces=True, return_representation=True)
    print("energy:", out["energy"])
    print("forces:", out["forces"].shape)
