import torch
import time
import sys
import os

# Add project root to path
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from src.spectra.models.backbones.cgnn.algebra import get_algebra

def get_random_multivector(batch_size=1):
    return torch.randn(batch_size, 8)

def test_algebra_properties():
    print("\n--- 1. Algebraic Correctness Tests ---")
    alg = get_algebra()
    
    # 1.1 Cayley Table Spot Checks
    e1 = torch.zeros(8); e1[1] = 1
    e2 = torch.zeros(8); e2[2] = 1
    e12 = torch.zeros(8); e12[4] = 1
    
    prod = alg.geometric_product(e1, e2)
    err = (prod - e12).abs().max()
    print(f"e1 * e2 == e12: {'✅' if err < 1e-6 else '❌'} (err={err:.2e})")
    
    prod2 = alg.geometric_product(e1, e1) # scalar 1
    if abs(prod2[0] - 1.0) < 1e-6:
        print(f"e1 * e1 == 1:   ✅")
    else:
        print(f"e1 * e1 == 1:   ❌ ({prod2})")

    # 1.2 Associativity (A B) C == A (B C)
    A = get_random_multivector(10)
    B = get_random_multivector(10)
    C = get_random_multivector(10)
    
    AB_C = alg.geometric_product(alg.geometric_product(A, B), C)
    A_BC = alg.geometric_product(A, alg.geometric_product(B, C))
    
    assoc_err = (AB_C - A_BC).abs().max()
    print(f"Associativity:  {'✅' if assoc_err < 1e-5 else '❌'} (err={assoc_err:.2e})")
    
    # 1.3 Distributivity A (B + C) == A B + A C
    lhs = alg.geometric_product(A, B + C)
    rhs = alg.geometric_product(A, B) + alg.geometric_product(A, C)
    dist_err = (lhs - rhs).abs().max()
    print(f"Distributivity: {'✅' if dist_err < 1e-5 else '❌'} (err={dist_err:.2e})")

def test_equivariance():
    print("\n--- 2. Equivariance Tests (O(3)) ---")
    # Define rotation
    theta = torch.tensor(3.14159 / 4.0) # 45 deg
    # Rotation in XY plane (generated by bivector e12)
    # R = exp(-theta/2 * e12) = cos(theta/2) - sin(theta/2) e12
    c = torch.cos(theta/2)
    s = torch.sin(theta/2)
    R = torch.zeros(8)
    R[0] = c
    R[4] = -s 
    
    # Inverse R_inv = cos + sin e12
    R_inv = torch.zeros(8)
    R_inv[0] = c
    R_inv[4] = s
    
    alg = get_algebra()
    
    # Input Multivector M
    M = get_random_multivector(1)
    
    # 1. Sandwich Product: M_rot = R M R_inv
    M_rot = alg.geometric_product(alg.geometric_product(R, M), R_inv)
    
    # 2. Manual Rotation of Components
    # Vector v should rotate by theta in XY plane
    # v_x' = vx cos - vy sin
    # v_y' = vx sin + vy cos
    v = M[:, 1:4].clone()
    v_rot_expected = v.clone()
    ct, st = torch.cos(theta), torch.sin(theta)
    v_rot_expected[:, 0] = v[:, 0]*ct - v[:, 1]*st
    v_rot_expected[:, 1] = v[:, 0]*st + v[:, 1]*ct
    
    # Compare computed v from Sandwich vs Expected
    v_rot_sandwich = M_rot[:, 1:4]
    
    err_v = (v_rot_sandwich - v_rot_expected).abs().max()
    print(f"Vector Rotation:   {'✅' if err_v < 1e-5 else '❌'} (err={err_v:.2e})")
    
    # Check Scalar Invariance
    err_s = (M[:, 0] - M_rot[:, 0]).abs().max()
    print(f"Scalar Invariance: {'✅' if err_s < 1e-5 else '❌'} (err={err_s:.2e})")
    
    # Check Pseudoscalar Invariance (under Rotation)
    err_t = (M[:, 7] - M_rot[:, 7]).abs().max()
    print(f"Pseudo Invariance: {'✅' if err_t < 1e-5 else '❌'} (err={err_t:.2e})")

def optimized_gp_vector(M, v_edge):
    """
    M: [..., 8] (Full)
    v_edge: [..., 3] (Only vector part of E)
    Computes M * E where E = (0, v, 0, 0)
    """
    s = M[..., 0:1]
    v = M[..., 1:4]
    b = M[..., 4:7] # e12, e23, e31
    t = M[..., 7:8]
    
    vx, vy, vz = v_edge[..., 0:1], v_edge[..., 1:2], v_edge[..., 2:3]
    
    # Algebra rules for Cl(3,0)
    # v * v' = v.v' + v ^ v'
    
    # 1. Grade 0 (Scalar): v . v_edge
    # Note: v . v_edge is sum(v_i * u_i)
    # But gp(v, v') = v_i e_i * v_j e_j. If i=j, e_i e_i = 1.
    # So scalar part is dot product.
    out_s = (v * v_edge).sum(dim=-1, keepdim=True)
    
    # 2. Grade 1 (Vector): s * v_edge + b * v_edge + t * v_edge
    # s * v_edge -> simple scale
    term1 = s * v_edge
    
    # b * v_edge -> b . v_edge (Vector) + b ^ v_edge (Trivector)
    # b = b12 e12 + b23 e23 + b31 e31
    # v = x e1 + y e2 + z e3
    # e12 e1 = -e2, e12 e2 = e1, e12 e3 = e123
    # ...
    # This is effectively (Dual(b) x v) for vector part?
    # Let's use cross product logic.
    # b . v:
    # (b4 e12 + b5 e23 + b6 e31) * (v1 e1 + v2 e2 + v3 e3)
    # b4 e12 e1 = -b4 v1 e2
    # b4 e12 e2 = b4 v2 e1
    # b4 e12 e3 = b4 v3 e123 (Trivector)
    # ...
    # Vector part of b*v:
    # e1 component: b4 v2 (from e12 e2) - b6 v3 (from e31 e3)
    # e2 component: -b4 v1 (from e12 e1) + b5 v3 (from e23 e3)
    # e3 component: -b5 v2 (from e23 e2) + b6 v1 (from e31 e1)
    
    # This looks like Cross Product of "Dual b" and v?
    # Dual b = (b23, b31, b12) -> (b5, b6, b4)
    # Cross((b5, b6, b4), (v1, v2, v3)):
    # x: b6 v3 - b4 v2 (Sign mismatch?)
    # Let's just implement explicit mults
    b12, b23, b31 = b[..., 0:1], b[..., 1:2], b[..., 2:3]
    v1, v2, v3 = vx, vy, vz
    
    out_v1 = b12 * v2 - b31 * v3
    out_v2 = -b12 * v1 + b23 * v3
    out_v3 = -b23 * v2 + b31 * v1
    
    term2 = torch.cat([out_v1, out_v2, out_v3], dim=-1)
    
    out_v = term1 + term2
    
    # 3. Grade 2 (Bivector): v ^ v_edge + t * v_edge
    # v ^ v_edge is outer product (Standard Cross Product duality)
    # Cross(v, v_edge):
    # cx = v2 v3' - v3 v2' -> e23 component (b5)
    # cy = v3 v1' - v1 v3' -> e31 component (b6)
    # cz = v1 v2' - v2 v1' -> e12 component (b4)
    
    cross = torch.cross(v, v_edge, dim=-1) # [cx, cy, cz]
    # Map to bivector indices [4, 5, 6] -> [e12, e23, e31]
    # out_b4 (e12) = cz
    # out_b5 (e23) = cx
    # out_b6 (e31) = cy
    out_b_from_v = torch.cat([cross[..., 2:3], cross[..., 0:1], cross[..., 1:2]], dim=-1)
    
    # t * v_edge
    # t e123 * (v1 e1 + ...)
    # e123 e1 = e23 (b5)
    # e123 e2 = e31 (b6)
    # e123 e3 = e12 (b4)
    out_b_from_t = torch.cat([t*v3, t*v1, t*v2], dim=-1)
    
    out_b = out_b_from_v + out_b_from_t
    
    # 4. Grade 3 (Trivector): b ^ v_edge
    # b4 e12 e3 = b4 v3 e123
    # b5 e23 e1 = b5 v1 e123
    # b6 e31 e2 = b6 v2 e123
    out_t = b12 * v3 + b23 * v1 + b31 * v2
    
    return torch.cat([out_s, out_v, out_b, out_t], dim=-1)

def benchmark_optimization():
    print("\n--- 3. Performance Benchmark ---")
    alg = get_algebra()
    if torch.cuda.is_available():
        alg.cuda()
    
    B = 10000
    M = get_random_multivector(B).cuda()
    v_edge = torch.randn(B, 3).cuda()
    E = torch.zeros(B, 8).cuda()
    E[:, 1:4] = v_edge
    
    # Warmup
    for _ in range(10):
        _ = alg.geometric_product(M, E)
        _ = optimized_gp_vector(M, v_edge)
    
    # Bench Einsum
    torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(100):
        _ = alg.geometric_product(M, E)
    torch.cuda.synchronize()
    t_einsum = (time.time() - t0) / 100
    
    # Bench Optimized
    torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(100):
        _ = optimized_gp_vector(M, v_edge)
    torch.cuda.synchronize()
    t_opt = (time.time() - t0) / 100
    
    print(f"Einsum GP:    {t_einsum*1000:.3f} ms")
    print(f"Optimized GP: {t_opt*1000:.3f} ms")
    print(f"Speedup:      {t_einsum/t_opt:.2f}x")
    
    # Verify Correctness
    res_einsum = alg.geometric_product(M, E)
    res_opt = optimized_gp_vector(M, v_edge)
    err = (res_einsum - res_opt).abs().max()
    print(f"Optimization Correctness: {'✅' if err < 1e-5 else '❌'} (err={err:.2e})")

if __name__ == "__main__":
    if torch.cuda.is_available():
        test_algebra_properties()
        test_equivariance()
        benchmark_optimization()
    else:
        print("Skipping benchmark (No CUDA)")
        test_algebra_properties()
        test_equivariance()
